apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  secretkey1: cGFzc3dvcmQ=
  secretkey2: c2VjcmV0c2VjcmV0

## We have to base64 encode our secret values using echo -n 'password' | base64 
